### ISSUE TITLE
Is there any way to overlay numerical information directly on Reactome diagrams?

### ISSUE THREAD

**Issue by kkami1115** [reactome/ReactomeContentService4R#29]
I would like to overlay gene expression levels (RNA-seq, TPM) or log2FC on some pathway images of reactome.

Even in this case, is the only way to do this is to perform the analysis from [{ReactomeGSA}](https://github.com/reactome/ReactomeGSA), get the token, and then output the image using exportImage() of {ReactomeContentService4R}? 
Or is there a way to overlay the numerical information directly on the pathway image?

I'm still not familiar with your packages, so I apologize if there's any documentation to it.

Thanks, 
@kkami1115

**Comment by chilampoon** [comment]
Yup you can first perform analysis with ReactomeGSA then output the overlay diagram ;)

Or can try the Pathvisio/SBGNview mentioned in this biostar post: [Is there a way to visualize log fold changes for Reactome pathways in R?](https://www.biostars.org/p/378003/#490937)

One more alternative is to manually add something you like (numbers, layers, etc) to the exported reatcome diagram since the output is a magick object, examples see the magick [vignette](https://cran.r-project.org/web/packages/magick/vignettes/intro.html). 
e.g. get a diagram `img <- exportImage(id="R-HSA-169911")`, then do the magick processing

**Comment by kkami1115** [comment]
Okay, I've done some research from your suggests so I'll take a look at it.
Thanks for answering my question.
